version: '3'

tasks:
  lib:
    cmds:
      - npx nx run-many -t build interfaces database schemas
  api:
    cmds:
      - npx nx run api:serve

  register-user:
    cmds:
      - npx nx run register-user:build && node ./dist/apps/register-user/main

  subscription:
    cmds:
      - npx nx run subscription:build && node ./dist/apps/subscription/main

  all:
    cmds:
      - npx nx run-many -t serve api register-user subscription

