version: '3'

tasks:
  lib:
    cmds:
      - npx nx run-many -t build interfaces database schemas

  sync:
    cmds:
      - node scripts/syncinterface

  api:
    cmds:
      - npx nx run api:serve

  register-user:
    cmds:
      - npx nx run register-user:build && node ./dist/apps/register-user/main

  subscription:
    cmds:
      - npx nx run subscription:build && node ./dist/apps/subscription/main

  payment:
    cmds:
      - npx nx run payment:build && node ./dist/apps/payment/main

  appointment:
    cmds:
      - npx nx run appointment:build && node ./dist/apps/appointment/main

  demo:
    cmds:
      - npx nx run-many -t serve api register-user subscription payment appointment --parallel=5

